version: '3'
services:
  app:
    build:
      context: .
      dockerfile: config/docker/Dockerfile
    environment:
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    tty: true
    command: bash -c "rm -f tmp/pids/server.pid && ./bin/dev"
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bank_development
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
